name: CI Message

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send KakaoTalk notification
        if: failure()  # Uncommented the conditional execution
        uses: Alfex4936/kakaotalk-ci-action@main
        with:
          kakao_access_token: ${{ secrets.KAKAO_ACCESS_TOKEN }}
          function_name: send_to_me_custom
          template_id: "109803"
          # template_args: '{"title": "${{ github.event_name }}", "desc": "${{ github.event_name }}! Please check it."}'
          # template_args: '{"title": "${{ github.event_name }}", "desc": "${{ github.event.head_commit.message }}"}'
          template_args: '{"title": "${{ github.event_name }}", "desc": "${{ env.COMMIT_MESSAGE }}"}'
          
