name: Backend Discord Webhook Notify

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification
      if: always()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: ${{ job.status == 'success' && 'info' || 'error' }}
        details: |
          **Backend Repository: Workflow Notification**
          Repository: ${{ github.repository }}
          Event: ${{ github.event_name }}
          Ref: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Actor: ${{ github.actor }}
          Status: ${{ job.status }}
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
